# Generated by Django 4.2.27 on 2025-12-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_csv_path",
                    models.CharField(
                        help_text="Path to the source CSV file in storage",
                        max_length=500,
                    ),
                ),
                (
                    "selection",
                    models.JSONField(
                        help_text="Selected FIO columns and mode (single/split)"
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        blank=True,
                        help_text="Detected CSV encoding",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        help_text="Detected CSV delimiter",
                        max_length=5,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_id",
                    models.PositiveIntegerField(
                        help_text="1-based row number in the source CSV"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Target field name (fio, first_name, last_name, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "before_value",
                    models.TextField(
                        blank=True, help_text="Original value before suggestion"
                    ),
                ),
                (
                    "suggested_value",
                    models.TextField(help_text="Proposed corrected value"),
                ),
                (
                    "suggestion_code",
                    models.CharField(
                        help_text="Machine-readable suggestion reason code",
                        max_length=100,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "high"), ("medium", "medium")], max_length=10
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Human-readable explanation of the suggestion"
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        help_text="Structured evidence supporting the suggestion",
                        null=True,
                    ),
                ),
                (
                    "generator",
                    models.CharField(
                        help_text="Suggestion generator identifier", max_length=100
                    ),
                ),
                (
                    "generator_version",
                    models.CharField(
                        help_text="Version of the suggestion generator", max_length=50
                    ),
                ),
                (
                    "dictionary_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the dictionary version used, if applicable",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("proposed", "proposed"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("edited", "edited"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "decision_value",
                    models.TextField(
                        blank=True,
                        help_text="Final value chosen by the user, if edited",
                        null=True,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="fio_runstore.run",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="suggestion",
            constraint=models.UniqueConstraint(
                fields=(
                    "run",
                    "row_id",
                    "field_name",
                    "suggestion_code",
                    "suggested_value",
                ),
                name="uniq_suggestion_per_run_row_field_reason_value",
            ),
        ),
    ]
